tests: fix lib and cflags order in Makefile.am
pnm: add misssing continuation slash at end of line
vp8parser: no need to link codecparsers twice
dash_demux, mssdemux, hlsdemux: fix lib/flags ordering - local
libs and flags must come first, then base before core before rest

Fixes unit test linking error:
  CCLD     elements/dash_demux
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libgsttag-1.0.so: undefined reference to `gst_make_element_message_details'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libgsttag-1.0.so: undefined reference to `gst_element_message_full_with_details'